-- ============================================
-- FinanSaku Database Constraints
-- Manual CHECK constraints (not generated by Prisma)
-- ============================================

-- === UMK ===

ALTER TABLE "umk"
DROP CONSTRAINT IF EXISTS check_umk_amount_nonnegative;
ALTER TABLE "umk"
ADD CONSTRAINT check_umk_amount_nonnegative
CHECK (amount >= 0);

-- === Allocation Templates ===

ALTER TABLE "allocation_templates"
DROP CONSTRAINT IF EXISTS check_allocation_templates_persona_valid;
ALTER TABLE "allocation_templates"
ADD CONSTRAINT check_allocation_templates_persona_valid
CHECK (persona IN (
  'mahasiswa',
  'pekerja_rantau',
  'first_jobber',
  'keluarga_muda',
  'freelancer'
)); -- TODO: Tentative validations. Do more research.

-- === Budget Categories ===

ALTER TABLE "budget_categories"
DROP CONSTRAINT IF EXISTS check_budget_categories_default_percentage_valid;
ALTER TABLE "budget_categories"
ADD CONSTRAINT check_budget_categories_default_percentage_valid
CHECK (default_percentage IS NULL OR (default_percentage >= 0 AND default_percentage <= 100));

-- === Budget Subcategories ===

ALTER TABLE "budget_subcategories"
DROP CONSTRAINT IF EXISTS check_budget_subcategories_default_percentage_valid;
ALTER TABLE "budget_subcategories"
ADD CONSTRAINT check_budget_subcategories_default_percentage_valid
CHECK (default_percentage >= 0 AND default_percentage <= 100);

-- === Saku ===

ALTER TABLE "saku"
DROP CONSTRAINT IF EXISTS check_saku_salary_nonnegative;
ALTER TABLE "saku"
ADD CONSTRAINT check_saku_salary_nonnegative
CHECK (salary IS NULL OR salary >= 0);

-- === Saku Allocations ===

ALTER TABLE "saku_allocations"
DROP CONSTRAINT IF EXISTS check_saku_allocations_percentage_valid;
ALTER TABLE "saku_allocations"
ADD CONSTRAINT check_saku_allocations_percentage_valid
CHECK (percentage IS NULL OR (percentage >= 0 AND percentage <= 100));

ALTER TABLE "saku_allocations"
DROP CONSTRAINT IF EXISTS check_saku_allocations_fixed_amount_nonnegative;
ALTER TABLE "saku_allocations"
ADD CONSTRAINT check_saku_allocations_fixed_amount_nonnegative
CHECK (fixed_amount IS NULL OR fixed_amount >= 0);

ALTER TABLE "saku_allocations"
DROP CONSTRAINT IF EXISTS check_saku_allocations_amount_nonnegative;
ALTER TABLE "saku_allocations"
ADD CONSTRAINT check_saku_allocations_amount_nonnegative
CHECK (amount >= 0);

-- === Calendar Events ===

ALTER TABLE "calendar_events"
DROP CONSTRAINT IF EXISTS check_calendar_events_expected_amount_nonnegative;
ALTER TABLE "calendar_events"
ADD CONSTRAINT check_calendar_events_expected_amount_nonnegative
CHECK (expected_amount IS NULL OR expected_amount >= 0);

ALTER TABLE "calendar_events"
DROP CONSTRAINT IF EXISTS check_calendar_events_status_valid;
ALTER TABLE "calendar_events"
ADD CONSTRAINT check_calendar_events_status_valid
CHECK (status IN ('pending', 'done', 'skipped'));

-- === Notifications ===

ALTER TABLE "notifications"
DROP CONSTRAINT IF EXISTS check_notifications_type_valid;
ALTER TABLE "notifications"
ADD CONSTRAINT check_notifications_type_valid
CHECK (type IN ('reminder', 'system', 'survey', 'budget'));

ALTER TABLE "notifications"
DROP CONSTRAINT IF EXISTS check_notifications_notifiable_type_valid;
ALTER TABLE "notifications"
ADD CONSTRAINT check_notifications_notifiable_type_valid
CHECK (notifiable_type IS NULL OR notifiable_type IN (
  'saku',
  'calendar_event',
  'budget',
  'announcement',
  'system',
  'survey'
));

-- === Admins ===

ALTER TABLE "admins"
DROP CONSTRAINT IF EXISTS check_admins_role_valid;
ALTER TABLE "admins"
ADD CONSTRAINT check_admins_role_valid
CHECK (role IN (
  'super_admin',
  'system_admin',
  'content_admin',
  'finance_admin',
  'moderator',
  'support'
));

-- === Announcements ===

ALTER TABLE "announcements"
DROP CONSTRAINT IF EXISTS check_announcements_audience_scope_valid;
ALTER TABLE "announcements"
ADD CONSTRAINT check_announcements_audience_scope_valid
CHECK (audience_scope IN ('all', 'by_user', 'by_persona', 'by_city'));

ALTER TABLE "announcements"
DROP CONSTRAINT IF EXISTS check_announcements_type_valid;
ALTER TABLE "announcements"
ADD CONSTRAINT check_announcements_type_valid
CHECK (type IN ('system', 'budget', 'survey', 'reminder'));

ALTER TABLE "announcements"
DROP CONSTRAINT IF EXISTS check_announcements_notifiable_type_valid;
ALTER TABLE "announcements"
ADD CONSTRAINT check_announcements_notifiable_type_valid
CHECK (notifiable_type IS NULL OR notifiable_type IN (
  'saku',
  'calendar_event',
  'budget',
  'announcement',
  'system',
  'survey'
));

ALTER TABLE "announcements"
DROP CONSTRAINT IF EXISTS check_announcements_status_valid;
ALTER TABLE "announcements"
ADD CONSTRAINT check_announcements_status_valid
CHECK (status IN ('draft', 'scheduled', 'sent', 'cancelled'));
